### ISSUE TITLE
[중복번역혼선] - 기존에 번역된 내용들 검토 후 반영부탁합니다. 

### ISSUE THREAD

**Issue by hygjob** [keras-team/keras-docs-ko#104]
안녕하세요 좋은 자료와 번역을 통해 KERAS에 대해 잘 알게 되어 좋네요.

clone하고 번역을 했더니 이미 기존 PR에 번역된 내용이 많이 있네요.
바쁘시겠지만 검토해서 master 에 반영해 주시면 중복 번역하는 혼선이 없을 것 같습니다.

**Comment by fuzzythecat** [comment]
현재 모든 문서에 대한 1차 번역은 완료되어 있습니다!
