### ISSUE TITLE
Keras/docker/README.md 번역

### ISSUE THREAD

**Issue by buildthan** [keras-team/keras-docs-ko#107]
# Using Keras via Docker

이 디렉토리는 [Docker](http://www.docker.com/) 을 통해 케라스를 실행시키기 쉽게 만들기 위해 ‘Docker파일’을 포함하고 있습니다.

## Installing Docker

일반적인 설치 방법은 [Docker 사이트](https://docs.docker.com/installation/)
 에 있지만, 빠른 설치를 위한 링크를 제공하고 있습니다.

* [OSX](https://docs.docker.com/installation/mac/): [docker toolbox](https://www.docker.com/toolbox)
* [ubuntu](https://docs.docker.com/installation/ubuntulinux/)

## Running the container

저희는 make 명령어 이내의 docker 명령어를 간단하게 만들기 위해 ‘makefile’을 사용하고 있습니다.

컨테이너를 빌드한 뒤 Jupyter Notebook을 실행시키십시오.

	$ make notebook

컨테이너를 빌드한 뒤 ipython shell을 실행시키십시오.

	$ make ipython

컨테이너를 빌드한 뒤 bash를 실행시키십시오.

	$ make bash

GPU 서포트를 위해 NVIDIA 드라이버와 (가능한 최신버젼으로) [nvidia-docker](https://github.com/NVIDIA/nvidia-docker)을 설치하십시오.
다음을 통해 실행시킵니다.

	$ make notebook GPU=0 # or [ipython, bash]

Theano 와 Tensorflow 을 번갈아 가며 고르십시오

	$ make notebook BACKEND=theano
	$ make notebook BACKEND=tensorflow

외부 데이터 셋을 위해 용량을 늘리십시오.

	$ make DATA=~/mydata

모든 make task들을 출력합니다.

	$ make help

당신은 `/docker/theanorc`을 편집함으로써 Theano 매개변수들을 변경할 수 있습니다.

참고사항: 만약 당신이 nvidia-docker을 실행시키는데 문제를 겪고 있다면, 저희가 사용해왔던 이전 방법을 알려드리겠습니다. 하지만 추천하는 방법은 아닙니다. Nvidia-docker에서 버그를 찾아낸다면 그곳에 버그를 신고하고 위에 설명된 예시처럼 nvidia-docker을 사용해보십시오.

	$ export CUDA_SO=$(\ls /usr/lib/x86_64-linux-gnu/libcuda.* | xargs -I{} echo '-v {}:{}')
	$ export DEVICES=$(\ls /dev/nvidia* | xargs -I{} echo '--device {}:{}')
	$ docker run -it -p 8888:8888 $CUDA_SO $DEVICES gcr.io/tensorflow/tensorflow:latest-gpu

**Comment by fuzzythecat** [comment]
번역을 PR로 부탁드려요!
